config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts

  root 'posts#index'

  get '/publisher' => 'publisher#index'
  get '/publisher/upload' => 'publisher#upload'

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id           :integer          not null, primary key
#  image        :string
#  title        :string
#  tagline      :string
#  url          :string
#  sort_order   :integer
#  scheduled_at :datetime
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Post < ActiveRecord::Base
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime
#  updated_at             :datetime
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # :database_authenticatable, :registerable,
  # :recoverable, :rememberable, :trackable, :validatable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to posts_path, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:image, :title, :tagline, :url, :sort_order, :scheduled_at)
    end
end

app/controllers/publisher_controller.rb
class PublisherController < ApplicationController

  before_action :authenticate_user!
  before_action :set_service, only: [:index, :upload]

  def index
    respond_to do |format|
      format.html
    end
  end

  def upload

    @publisher_service.upload

    respond_to do |format|
      if @publisher_service.status
        format.html { redirect_to publisher_path, notice: 'JSON content is published.'}
      else
        format.html { redirect_to publisher_path, notice: "Error: #{@publisher_service.error_message}"}
      end
    end
  end

  private

  def set_service
    @publisher_service = PublisherService.new()
    @json = @publisher_service.json()
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.haml
.footer
  - unless ['sessions', 'passwords'].include?(controller_name)
    %hr
    Feedback is welcome:
    =link_to "Zoltan Debre", "http://zoltan.nz"
    |
    =link_to "LinkedIn", "http://www.linkedin.com/in/zoltandebre"
    |
    =link_to "Twitter", "http://twitter.com/szines"
    |
    =link_to "GitHub", "http://github.com/szines"

app/views/layouts/_header.html.haml
%nav.navbar.navbar-inverse
  .navbar-header
    %button.navbar-toggle{data: {toggle: 'collapse', target: '#menubar'}}
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    =link_to 'Admin', root_path, class: 'navbar-brand'
  #menubar.navbar-collapse.collapse
    %ul.nav.navbar-nav
      - if user_signed_in?
        %li=link_to 'Home', root_path, class: ('active' if controller_name == 'posts')
        %li=link_to 'Publishing', publisher_path, class: ('active' if controller_name == 'publisher')
    %ul.nav.navbar-nav.navbar-right
      - if user_signed_in?
        %li=link_to('Logout', destroy_user_session_path, method: :delete)
=render 'layouts/messages'

app/views/layouts/_messages.html.haml
-flash.each do |name, msg|
  %div{class: "alert alert-#{name == :notice ? "success" : "danger"}"}
    %button.close{data: {dismiss: 'alert'}} ×
    - if msg.is_a?(String)
      =content_tag :div, msg, id: "flash_#{name}"
    - if msg.is_a?(Array)
      - msg.each do |m|
        =content_tag :div, m

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: 'width=device-width, initial-scale=1', name: 'viewport'}
    %title Admin
    = favicon_link_tag 'favicon.ico'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body{class: controller_name}
    .container
      = render 'layouts/header'
      = yield
      = render 'layouts/footer'

    - if ['sessions', 'passwords'].include?(controller_name)
      .image-holder

app/views/posts/_form.html.haml
.row
  .col-md-8.col-md-offset-2
    =form_for @post, html: {class: 'form-horizontal'} do |f|
      .form-group.form-group-lg
        =f.label :image, 'Image:', class: 'col-sm-2 control-label'
        .col-sm-10
          =f.text_field :image, class: 'form-control input-lg', autofocus: true, placeholder: 'Image url'
      .form-group.form-group-lg
        =f.label :title, 'Title:', class: 'col-sm-2 control-label'
        .col-sm-10
          =f.text_field :title, class: 'form-control input-lg', placeholder: 'Title'
      .form-group.form-group-lg
        =f.label :tagline, 'Tagline:', class: 'col-sm-2 control-label'
        .col-sm-10
          =f.text_field :tagline, class: 'form-control input-lg', placeholder: 'Tagline'
      .form-group.form-group-lg
        =f.label :url, 'Url:', class: 'col-sm-2 control-label'
        .col-sm-10
          =f.text_field :url, class: 'form-control input-lg', placeholder: 'Url'
      .form-group
        .col-sm-offset-2.col-sm-10
          =button_tag 'Reset', type: :reset, class: 'btn'
          =f.submit (@post.new_record? ? 'Create' : 'Update'), class: 'btn btn-success'
.row
  .col-md-12
    .well.well-small
      =link_to '<< Back to the list', posts_path

app/views/posts/_list.html.haml
%table.table.table-bordered.table-hover.posts-list

  %thead
    %th #
    %th Image
    %th Title
    %th Tagline
    %th Url
    %th.column-actions Actions

  %tbody
    - @posts.each do |post|
      %tr
        %td=post.id
        %td=post.image
        %td=post.title
        %td=post.tagline
        %td=post.url
        %td.text-right.column-actions
          =link_to 'Edit', edit_post_path(post), class: 'btn btn-success'
          =link_to 'X', post_path(post), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger'

app/views/posts/edit.html.haml
%h1 Editing Post
= render 'form'

app/views/posts/index.html.haml
=link_to 'Create accouncement', new_post_path, class: 'btn btn-primary pull-right'

%h1 List of Announcements

=render 'list'

app/views/posts/new.html.haml
%h1 New Post
= render 'form'

app/views/posts/show.html.haml
=@post.id
=@post.image
=@post.title
=@post.tagline
=@post.url
=@post.sort_order
=@post.scheduled_at

= link_to 'Edit', edit_post_path(@post)
|
= link_to 'Back', posts_path

app/views/publisher/index.html.haml
%h1 Publishing

%h3 Preview of generated JSON file

.well
  %code
    = @json

%h3 Upload

.well
  .row
    .col-md-10
      Double check JSON code above. Clicking on Publish button will upload the code to Amazon AWS and the content will be published immediately.
    .col-md-2
      =link_to 'Publish', publisher_upload_path, class: 'btn btn-danger btn-lg pull-right'

%h3 Amazon AWS content

.well
  Link to the uploaded JSON file:
  %a{href: ENV['S3_URL']} Link

app/views/publisher/upload.html.haml
Upload...

=   @response